apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pillar.fullname" . }}-secret-refs
  labels:
{{ include "pillar.labels" . | indent 4 }}
    app.kubernetes.io/component: secret-refs
type: Opaque
stringData:
  EXTERNAL_SECRET_NAME: {{ include "pillar.fullname" . }}-runtime
