apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pillar-template-registry
spec:
  replicas: {{ .Values.templateRegistry.replicas }}
  selector: { matchLabels: { app: pillar-template-registry } }
  template:
    metadata: { labels: { app: pillar-template-registry } }
    spec:
      serviceAccountName: {{ .Release.Name }}-pillar-template-registry
      containers:
        - name: template-registry
          image: "{{ .Values.templateRegistry.image.repository }}:{{ .Values.templateRegistry.image.tag }}"
          ports: [{ containerPort: 8087, name: http }]
          envFrom: [{ configMapRef: { name: {{ .Release.Name }}-pillar-template-registry } }]
