import { createHash } from 'node:crypto';
import type pg from 'pg';
type Claim = { status: 'new'|'in_progress'|'completed'|'conflict'; stored?: { response_status: number; response_body: unknown } };
function hashKey(key:string){return createHash('sha256').update(key).digest('hex');}
function lockBigint(hash:string){return BigInt.asIntN(64, BigInt('0x'+hash.slice(0,16))).toString();}
export class IdempotencyStore { constructor(private pool: pg.Pool, private ttlMs=24*3600_000) {}
 async claim(tenant_id:string, key:string, request_hash:string): Promise<Claim> { const h=hashKey(key); const c=await this.pool.connect(); try { await c.query('BEGIN'); const got=await c.query('select pg_try_advisory_xact_lock($1::bigint) ok',[lockBigint(h)]); if(!got.rows[0].ok){ await c.query('ROLLBACK'); return {status:'in_progress'}; } const r=await c.query('select * from idempotency_keys where tenant_id=$1 and idempotency_key_hash=$2 for update',[tenant_id,h]); if(!r.rowCount){ await c.query("insert into idempotency_keys(tenant_id,idempotency_key_hash,request_hash,method,path_template,api_version,status,locked_until,expires_at) values($1,$2,$3,'POST','unknown','unknown','in_progress',now()+interval '5 minutes',$4)",[tenant_id,h,request_hash,new Date(Date.now()+this.ttlMs)]); await c.query('COMMIT'); return {status:'new'}; } const row=r.rows[0]; if(row.request_hash!==request_hash){ await c.query('COMMIT'); return {status:'conflict'}; } if(row.status==='completed') { await c.query('COMMIT'); return {status:'completed', stored:{response_status:row.response_status, response_body:row.response_body}}; } if(row.locked_until && new Date(row.locked_until).getTime() < Date.now()) { await c.query("update idempotency_keys set locked_until=now()+interval '5 minutes', updated_at=now() where tenant_id=$1 and idempotency_key_hash=$2",[tenant_id,h]); await c.query('COMMIT'); return {status:'new'}; } await c.query('COMMIT'); return {status:'in_progress'}; } catch(e){ await c.query('ROLLBACK'); throw e; } finally { c.release(); } }
 async complete(tenant_id:string,key:string,response_status:number,response_body:unknown){ const h=hashKey(key); await this.pool.query("update idempotency_keys set status='completed', response_status=$3, response_body=$4, locked_until=null, updated_at=now() where tenant_id=$1 and idempotency_key_hash=$2",[tenant_id,h,response_status,response_body]); }
 async release(tenant_id:string,key:string){ const h=hashKey(key); await this.pool.query("update idempotency_keys set locked_until=null, updated_at=now() where tenant_id=$1 and idempotency_key_hash=$2 and status<>'completed'",[tenant_id,h]); }
}
