apiVersion: v1
kind: ConfigMap
metadata: { name: {{ include "pillar.fullname" . }}-usage-meter }
data:
  DEPLOYMENT_MODE: {{ .Values.deploymentMode | quote }}
  STREAM_BACKEND: {{ .Values.usageMeter.streamBackend | default "redis" | quote }}
