{{- if .Values.usageMeter.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: { name: {{ include "pillar.fullname" . }}-usage-meter }
spec: {{ toYaml .Values.usageMeter.externalSecret.spec | nindent 2 }}
{{- end }}
