{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: {{ include "pillar.fullname" . }}-usage-meter }
spec: { selector: { matchLabels: { app.kubernetes.io/name: usage-meter } }, endpoints: [{ port: http }] }
{{- end }}
