module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'chore', 'docs', 'refactor', 'perf', 'test', 'build', 'ci', 'revert'],
    ],
    'scope-enum': [
      1,
      'always',
      [
        // Match docs/Dev/README.md §4 area letters
        'repo',
        'daml',
        'api',
        'db',
        'idempotency',
        'ledger',
        'projection',
        'webhook',
        'sdk',
        'cli',
        'workbench',
        'dashboard',
        'docs-site',
        'compose',
        'helm',
        'ci',
        'release',
        'security',
        'compliance',
        'files',
        'search',
        'export',
        'reporting',
        'template-registry',
        'usage',
        'billing',
        'onboarding',
        'observability',
        'runbooks',
        'config',
        'codegen',
        'infra',
      ],
    ],
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'body-max-line-length': [1, 'always', 200],
    'footer-max-line-length': [1, 'always', 200],
  },
};
