{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pillar.fullname" . }}-api-blue
  labels:
{{ include "pillar.componentLabels" (dict "root" . "component" "api") | indent 4 }}
    pillar.canton/color: blue
spec:
  selector:
{{ include "pillar.selectorLabels" (dict "root" . "component" "api") | indent 4 }}
    pillar.canton/color: {{ ternary "blue" "inactive" (eq .Values.blueGreen.activeColor "blue") }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
{{- end }}
