import type { FastifyInstance } from 'fastify';
import { ulid } from 'ulid';
import * as F from '@pillar/api-contracts/fixtures';
import { renderList } from '../../http/pagination.js';
import { event, hold, operation, now, nid } from './data.js';
import { presentApiKey, presentApiKeyCreate, presentEvent, presentHold, presentOperation, presentWebhookEndpoint, presentWebhookSecret } from '../../presenters/index.js';
export async function holdsRoutes(s:FastifyInstance){ s.post('/holds', async r=>presentHold(hold(r.auth.livemode,r.body))); s.get('/holds', async r=>renderList('/v1/holds',[presentHold(hold(r.auth.livemode))])); s.get('/holds/:id', async r=>presentHold({...hold(r.auth.livemode),id:(r.params as any).id})); s.post('/holds/:id/release', async r=>presentHold({...hold(r.auth.livemode),id:(r.params as any).id,status:'released'})); s.post('/holds/:id/cancel', async r=>presentHold({...hold(r.auth.livemode),id:(r.params as any).id,status:'released'})); }
export async function operationsRoutes(s:FastifyInstance){ s.get('/operations', async r=>renderList('/v1/operations',[presentOperation(operation(r.auth.livemode))])); s.get('/operations/:id', async r=>presentOperation({...operation(r.auth.livemode),id:(r.params as any).id})); }
export async function eventsRoutes(s:FastifyInstance){ s.get('/events', async r=>renderList('/v1/events',[presentEvent(event(r.auth.livemode))])); s.get('/events/:id', async r=>presentEvent({...event(r.auth.livemode),id:(r.params as any).id})); s.post('/events/:id/resend', async r=>presentEvent({...event(r.auth.livemode),id:(r.params as any).id})); s.post('/events/:id/replay', async r=>presentEvent({...event(r.auth.livemode),id:(r.params as any).id})); }
let endpoints:any[]=[]; export async function webhookEndpointsRoutes(s:FastifyInstance){ s.post('/webhook_endpoints', async r=>{const b=r.body as any; const we={...F.webhookEndpoint,id:nid('we_'),created:now(),livemode:r.auth.livemode,url:b.url,enabled_events:b.enabled_events??['*'],api_version:b.api_version??r.apiVersion,metadata:b.metadata??{}}; endpoints.push(we); return presentWebhookEndpoint(we)}); s.get('/webhook_endpoints', async r=>renderList('/v1/webhook_endpoints',endpoints.map(presentWebhookEndpoint))); s.get('/webhook_endpoints/:id', async r=>presentWebhookEndpoint(endpoints.find(e=>e.id===(r.params as any).id)??{...F.webhookEndpoint,id:(r.params as any).id})); s.post('/webhook_endpoints/:id', async r=>presentWebhookEndpoint({...F.webhookEndpoint,id:(r.params as any).id,...(r.body as any)})); s.post('/webhook_endpoints/:id/enable', async r=>presentWebhookEndpoint({...F.webhookEndpoint,id:(r.params as any).id,status:'enabled'})); s.post('/webhook_endpoints/:id/disable', async r=>presentWebhookEndpoint({...F.webhookEndpoint,id:(r.params as any).id,status:'disabled'})); s.post('/webhook_endpoints/:id/rotate_secret', async r=>presentWebhookSecret({id:(r.params as any).id,secret:`plr_whsec_${ulid()}`,last4:'last',created:now()})); s.post('/webhook_endpoints/:id/test', async r=>presentEvent(event(r.auth.livemode))); s.get('/webhook_endpoints/:id/deliveries', async r=>renderList(`/v1/webhook_endpoints/${(r.params as any).id}/deliveries`,[])); s.delete('/webhook_endpoints/:id', async(r,reply)=>reply.status(200).send({id:(r.params as any).id,object:'deleted',deleted:true})); }
export async function apiKeysRoutes(s:FastifyInstance){ s.post('/api_keys', async r=>presentApiKeyCreate({...F.apiKeyCreate,id:nid('ak_'),secret:`plr_sk_test_${ulid()}`,created:now(),livemode:r.auth.livemode,...(r.body as any)})); s.get('/api_keys', async r=>renderList('/v1/api_keys',[presentApiKey({...F.apiKey,created:now(),livemode:r.auth.livemode})])); s.get('/api_keys/:id', async r=>presentApiKey({...F.apiKey,id:(r.params as any).id,created:now(),livemode:r.auth.livemode})); s.post('/api_keys/:id/rotate', async r=>presentApiKeyCreate({...F.apiKeyCreate,id:(r.params as any).id,secret:`plr_sk_test_${ulid()}`,created:now(),livemode:r.auth.livemode})); s.post('/api_keys/:id/revoke', async r=>presentApiKey({...F.apiKey,id:(r.params as any).id,status:'revoked',created:now(),livemode:r.auth.livemode})); s.post('/api_keys/:id/expire', async r=>presentApiKey({...F.apiKey,id:(r.params as any).id,status:'expired',created:now(),livemode:r.auth.livemode})); }
