import type { Metadata } from 'next';
import { CodePane } from '@/components/apiref/CodePane';
import { ParamTable } from '@/components/apiref/ParamTable';

export const metadata: Metadata = { title: 'Idempotency API | Canton Pillar' };

export default function IdempotencyPage() {
  return <article className="space-y-10"><header className="space-y-4"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">Getting started</p><h1 className="text-4xl font-bold text-ink">Idempotency</h1><p className="text-lg text-slateMuted">Mutation endpoints require idempotency keys so retries are safe.</p></header><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Header</h2><CodePane language="http" code="Idempotency-Key: 9f2d1c8e-7a9c-4e6a-9fb9-f1a5c9f88b31" /><p className="text-slateMuted">Keys must be 1–255 characters. UUIDs or ULIDs are recommended.</p></section><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Scope</h2><ParamTable params={[{name:'account',type:'string',required:true,description:'Caller account scope.'},{name:'livemode',type:'boolean',required:true,description:'Test and live keys do not share scope.'},{name:'method',type:'string',required:true,description:'HTTP method.'},{name:'path',type:'string',required:true,description:'Request path.'},{name:'key',type:'string',required:true,description:'Idempotency-Key value.'}]} /></section><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Conflicts and safety</h2><p className="text-slateMuted">Same key plus a different body returns idempotency_error. Missing keys on mutation return idempotency_key_required. Never put personal data, secrets, or private references in the key.</p><CodePane code={{ error: { type: 'idempotency_error', code: 'idempotency_key_reused', message: 'Idempotency key was reused with different parameters.', request_id: 'req_01J0F8Q4Y6B7C8D9E0F1G2H3J4', doc_url: 'https://docs.pillar.example/errors/idempotency_key_reused' } }} /></section></article>;
}
