import type { Metadata } from 'next';
import { CodePane } from '@/components/apiref/CodePane';
import { ParamTable } from '@/components/apiref/ParamTable';

export const metadata: Metadata = { title: 'Expand API | Canton Pillar' };

export default function ExpandPage() {
  return <article className="space-y-10"><header className="space-y-4"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">Getting started</p><h1 className="text-4xl font-bold text-ink">Expand</h1><p className="text-lg text-slateMuted">Selected endpoints can expand allowlisted related objects inline.</p></header><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Syntax</h2><ParamTable params={[{name:'expand[]',type:'array',description:'Repeatable query parameter.'},{name:'dotted notation',type:'string',description:'Use paths such as data.asset where allowed.'},{name:'max depth',type:'integer',description:'Nested expansion depth is capped per endpoint.'}]} /><CodePane language="bash" code={'curl https://api.pillar.example/v1/holdings/hldg_01J0F8P4A2B3C4D5E6F7G8H9J3?expand[]=asset \\\n  -H "Authorization: Bearer plr_sk_test_51HY..." \\\n  -H "Pillar-Version: 2026-05-26"'} /></section><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Allowlist</h2><p className="text-slateMuted">Each endpoint documents supported expansions. Unsupported entries return unsupported_expand instead of being ignored.</p><CodePane code={{ error: { type: 'invalid_request_error', code: 'unsupported_expand', message: 'Expansion is not supported for this endpoint.', request_id: 'req_01J0F8Q4Y6B7C8D9E0F1G2H3J4', doc_url: 'https://docs.pillar.example/errors/unsupported_expand' } }} /></section><section className="space-y-3"><h2 className="text-2xl font-bold text-ink">Admin-only expansion</h2><p className="text-slateMuted">Ledger trace expansion on operations is admin-only and gated by default. Public responses do not expose internal execution details.</p></section></article>;
}
