{{- if .Values.billingAdapter.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: { name: {{ include "pillar.fullname" . }}-billing-adapter }
spec: {{ toYaml .Values.billingAdapter.externalSecret.spec | nindent 2 }}
{{- end }}
