{{- if and .Values.validatorRegistry.enabled .Values.validatorRegistry.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pillar.fullname" . }}-validator-registry
spec: {{- toYaml .Values.validatorRegistry.externalSecret.spec | nindent 2 }}
{{- end }}
