import { randomBytes, createHash } from 'node:crypto';
import pg from 'pg';
import { ulid } from 'ulid';
import { signWebhookPayload, buildSignatureHeader } from '@pillar/security';
import { renderEvent } from '../events/rendering.js';

type Endpoint = any; type Delivery = any;
const endpoints = new Map<string, Endpoint>(); const deliveries = new Map<string, Delivery>(); const diagnostics: any[] = [];
const useMemory = () => process.env.PILLAR_DB === 'memory' || !process.env.DATABASE_URL;
let pool: pg.Pool | undefined;
function db() { return pool ??= new pg.Pool({ connectionString: process.env.DATABASE_URL }); }
const now = () => new Date().toISOString();
const secret = () => `plr_whsec_${randomBytes(24).toString('base64url')}`;
const hash = (v: string) => createHash('sha256').update(v).digest('hex');
function tenant(input: any) { const tenantId = input?.tenantId ?? input?.accountId; if (!tenantId) throw new Error('tenantId required'); return tenantId; }
function publicEndpoint(e: any) { const { secrets, signing_secret, tenant_id, secret_hash, ...rest } = e; return { id: e.id, object: 'webhook_endpoint', created: e.created ?? e.created_at ?? now(), livemode: !!e.livemode, url: e.url, enabled_events: e.enabled_events ?? ['*'], api_version: e.api_version, status: e.status ?? (e.enabled === false ? 'disabled' : 'enabled'), metadata: e.metadata ?? {}, secret_last4: e.secret_last4, ...rest }; }
function rowEndpoint(row: any) { return publicEndpoint({ ...row, created: row.created_at?.toISOString?.() ?? row.created_at, status: row.enabled ? 'enabled' : 'disabled' }); }
function seedEndpoint(id: string, tenantId: string) { const plaintext = 'plr_whsec_seed'; const e = { id, tenant_id: tenantId, object: 'webhook_endpoint', created: now(), livemode: false, url: 'https://example.com/webhooks', enabled_events: ['*'], api_version: '2026-05-26', status: 'enabled', metadata: {}, secret_last4: plaintext.slice(-4), secrets: [{ plaintext, hash: hash(plaintext), state: 'active', created: now() }] }; endpoints.set(`${tenantId}:${id}`, e); return e; }

export async function createEndpoint(input: any) {
  const tenantId = tenant(input); const plaintext = secret(); const id = `we_${ulid()}`;
  const e = { id, tenant_id: tenantId, object: 'webhook_endpoint', created: now(), livemode: !!input.livemode, url: input.url, enabled_events: input.enabled_events ?? ['*'], api_version: input.api_version ?? '2026-05-26', status: 'enabled', metadata: input.metadata ?? {}, secret_last4: plaintext.slice(-4), secrets: [{ hash: hash(plaintext), plaintext, state: 'active', created: now() }] };
  if (useMemory()) { endpoints.set(`${tenantId}:${id}`, e); return { ...publicEndpoint(e), secret: plaintext }; }
  await db().query('insert into webhook_endpoints(id, tenant_id, url, secret_hash, secret_last4, signing_secret, enabled, api_version) values($1,$2,$3,$4,$5,$6,true,$7)', [id, tenantId, input.url, hash(plaintext), plaintext.slice(-4), plaintext, e.api_version]);
  return { ...publicEndpoint(e), secret: plaintext };
}
export async function getEndpoint(id: string, tenantIdOrInput?: any) { const tenantId = tenant(typeof tenantIdOrInput === 'string' ? { tenantId: tenantIdOrInput } : tenantIdOrInput); if (useMemory()) return publicEndpoint(endpoints.get(`${tenantId}:${id}`) ?? seedEndpoint(id, tenantId)); const r = await db().query('select * from webhook_endpoints where tenant_id=$1 and id=$2 limit 1', [tenantId, id]); return r.rows[0] ? rowEndpoint(r.rows[0]) : null; }
export async function listEndpoints(input: any = {}) { const tenantId = tenant(input); if (useMemory()) return [...endpoints.values()].filter(e => e.tenant_id === tenantId).map(publicEndpoint); const r = await db().query('select * from webhook_endpoints where tenant_id=$1 order by created_at desc, id desc', [tenantId]); return r.rows.map(rowEndpoint); }
export async function updateEndpoint(id: string, input: any) { const tenantId = tenant(input); if (useMemory()) { const e = endpoints.get(`${tenantId}:${id}`) ?? seedEndpoint(id, tenantId); Object.assign(e, input); endpoints.set(`${tenantId}:${id}`, e); return publicEndpoint(e); } const current = await getEndpoint(id, tenantId); if (!current) return null; const next = { ...current, ...input }; await db().query('update webhook_endpoints set url=$3, api_version=$4, updated_at=now() where tenant_id=$1 and id=$2', [tenantId, id, next.url, next.api_version]); return next; }
export async function enableEndpoint(id: string, input: any = {}) { const tenantId = tenant(input); if (useMemory()) return updateEndpoint(id, { tenantId, status: 'enabled' }); await db().query('update webhook_endpoints set enabled=true, updated_at=now() where tenant_id=$1 and id=$2', [tenantId, id]); return getEndpoint(id, tenantId); }
export async function disableEndpoint(id: string, input: any = {}) { const tenantId = tenant(input); if (useMemory()) return updateEndpoint(id, { tenantId, status: 'disabled' }); await db().query('update webhook_endpoints set enabled=false, updated_at=now() where tenant_id=$1 and id=$2', [tenantId, id]); return getEndpoint(id, tenantId); }
export async function deleteEndpoint(id: string, input: any = {}) { return disableEndpoint(id, input); }
export async function rotateSecret(id: string, inputOrGrace: any = 24) { const input = typeof inputOrGrace === 'number' ? { graceHours: inputOrGrace } : inputOrGrace; const tenantId = tenant(input); const plaintext = secret(); if (useMemory()) { const e = endpoints.get(`${tenantId}:${id}`) ?? seedEndpoint(id, tenantId); e.secrets = [{ hash: hash(plaintext), plaintext, state: 'active', created: now() }]; e.secret_last4 = plaintext.slice(-4); endpoints.set(`${tenantId}:${id}`, e); return { id: e.id, secret: plaintext, last4: plaintext.slice(-4), created: now() }; } await db().query('update webhook_endpoints set secret_hash=$3, secret_last4=$4, signing_secret=$5, updated_at=now() where tenant_id=$1 and id=$2', [tenantId, id, hash(plaintext), plaintext.slice(-4), plaintext]); return { id, secret: plaintext, last4: plaintext.slice(-4), created: now() }; }
export async function listDeliveries(input: any = {}) { const tenantId = tenant(input); const endpointId = typeof input === 'string' ? undefined : input.endpointId; if (useMemory()) return [...deliveries.values()].filter(d => d.tenant_id === tenantId && (!endpointId || d.endpoint_id === endpointId || d.webhook_endpoint_id === endpointId)); const params = [tenantId] as any[]; let sql = 'select * from webhook_deliveries where tenant_id=$1'; if (endpointId) { params.push(endpointId); sql += ' and endpoint_id=$2'; } sql += ' order by created_at desc, id desc'; const r = await db().query(sql, params); return r.rows.map(rowDelivery); }
export async function getDelivery(id: string, input: any = {}) { const tenantId = tenant(input); if (useMemory()) return deliveries.get(`${tenantId}:${id}`) ?? null; const r = await db().query('select * from webhook_deliveries where tenant_id=$1 and id=$2 limit 1', [tenantId, id]); return r.rows[0] ? rowDelivery(r.rows[0]) : null; }
export async function requeueDelivery(id: string, input: any = {}) { const tenantId = tenant(input); if (useMemory()) { const old = deliveries.get(`${tenantId}:${id}`) ?? { tenant_id: tenantId, event_id: 'evt_01HY4Z7Z7Z7Z7Z7Z7Z7Z7Z7ZE', endpoint_id: 'we_01HY4Z7Z7Z7Z7Z7Z7Z7Z7Z7ZE' }; const d = { ...old, id: `wd_${ulid()}`, status: 'pending', attempt: 0, created: now() }; deliveries.set(`${tenantId}:${d.id}`, d); return d; } const old = await getDelivery(id, { tenantId }); if (!old) return null; const nextId = `wd_${ulid()}`; await db().query('insert into webhook_deliveries(id, tenant_id, event_id, endpoint_id, status, next_retry_at) values($1,$2,$3,$4,\'pending\',now())', [nextId, tenantId, old.event_id, old.endpoint_id ?? old.webhook_endpoint_id]); return getDelivery(nextId, { tenantId }); }
export async function dropDelivery(id: string, input: any = {}) { const tenantId = tenant(input); if (useMemory()) { const d = deliveries.get(`${tenantId}:${id}`) ?? { id, tenant_id: tenantId }; d.status = 'dropped'; deliveries.set(`${tenantId}:${id}`, d); return d; } await db().query("update webhook_deliveries set status='dropped', updated_at=now() where tenant_id=$1 and id=$2", [tenantId, id]); return getDelivery(id, { tenantId }); }
export async function enqueueTestPing(endpointId: string, input: any = {}) { const tenantId = tenant(input); const e: any = useMemory() ? (endpoints.get(`${tenantId}:${endpointId}`) ?? seedEndpoint(endpointId, tenantId)) : await loadEndpointInternal(tenantId, endpointId); if (!e) return null; const event = renderEvent({ id: `evt_${ulid()}`, type: 'webhook_endpoint.created', livemode: e.livemode, payload: { id: e.id, object: 'webhook_endpoint' }, request_id: 'req_01HY4Z7Z7Z7Z7Z7Z7Z7Z7Z7ZR' }, 'thin', e.api_version); const raw = Buffer.from(JSON.stringify(event)); const ts = Math.floor(Date.now() / 1000); const plaintext = e.secrets?.[0]?.plaintext ?? e.signing_secret; const sigs = plaintext ? [{ timestamp: ts, signature: signWebhookPayload(plaintext, ts, raw) }] : []; const deliveryId = `wd_${ulid()}`; if (useMemory()) deliveries.set(`${tenantId}:${deliveryId}`, { id: deliveryId, tenant_id: tenantId, event_id: event.id, endpoint_id: endpointId, status: 'pending', attempt: 0, created: now() }); else await db().query('insert into webhook_deliveries(id, tenant_id, event_id, endpoint_id, status, next_retry_at) values($1,$2,$3,$4,\'pending\',now())', [deliveryId, tenantId, event.id, endpointId]); return { event, raw_body_sha256: hash(raw.toString()), signature_header: buildSignatureHeader(sigs), delivery_id: deliveryId }; }
export async function recordDiagnostic(endpointId: string, result: any) { const row = { id: `diag_${ulid()}`, endpoint_id: endpointId, created: now(), classification: classify(result), ...result }; diagnostics.push(row); return row; }
function classify(r: any) { const url = String(r.url ?? ''); if (url.includes('timeout')) return 'timeout'; if (url.startsWith('http://')) return 'tls'; return r.status && r.status >= 300 && r.status < 400 ? 'redirect' : r.status ? 'http' : 'dns'; }
function rowDelivery(row: any) { return { ...row, object: 'webhook_delivery', webhook_endpoint_id: row.endpoint_id, created: row.created_at?.toISOString?.() ?? row.created_at, next_retry_at: row.next_retry_at?.toISOString?.() ?? row.next_retry_at }; }
async function loadEndpointInternal(tenantId: string, id: string) { const r = await db().query('select * from webhook_endpoints where tenant_id=$1 and id=$2 limit 1', [tenantId, id]); return r.rows[0]; }
